### ISSUE TITLE
Architecture can we do this

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/jsonld_forms#1]
https://docs.google.com/drawings/d/1S5Mywan0V7lVHzCDV0P9zjfVvXsOOsIkvsmF2U2NCI8/edit

Minio:
* authentication
* ability to restrict a group to a bucket 
* ability to restrict group to a sub bucket
* schedule workflow to push to a 'production' bucket
 
Useful:
* versioning

Workflow:
* user registers, is associated with a group
  *  group restricted to sub bucket
    * sub bucket rights assigned, so access granted to sub bucket granted
  * group can only be restricted to a bucket
    *  bucket created, rights assigned, access to bucket granted
* user creates file in UI, 
  * saves progress. File is pushed to minio sub bucket with a draft metadata flag. 
  * finalizes file, file pushed to bucket with publish metadata flag
* workflow pushes "publish" jsonld to production bucket, (and triggers push to triple store)
* workflow harasses about a draft. Do we want an I am just testing flag?

Admin UI
* users/group listing
* all files listing 
  * for a group
  * draft
* validation of a json file

Mino Documentation:
* https://docs.min.io/docs/minio-multi-user-quickstart-guide.html
   *  Policy Variables

**Comment by smrgeoinfo** [comment]
@valentinedwv -- First, just checking that these S3-like (e.g. Minio) buckets contain metadata that will be indexed for GeoCODES search.    
If so, one of the major sources of content will be Gleaner harvests.  The workflow you're describing would be for hand-crafted metadata records -- currently the source of content for the non-dataset resources (ECRR stuff).  I'm thinking the same pattern should be used for Dataset records. The forms edit interface should be designed to work with all the kinds of resources we're interested in indexing and linking through GeoCODES.

Will we allow editing of harvested records in the buckets?  If we are running some kind of enhancers, or fixing known issues (e.g. http vs. https) and updated bucket recoords, we could

- push updated records back to the source
- created a separate record that gets loaded as a separate graph linked to the original graph for the resource

**Comment by valentinedwv** [comment]
Yes we can. Policies

#### By User
For a user with no group, this will set a policy that publishes to thier directory

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": ["s3:ListBucket"],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::users"],
      "Condition": {"StringLike": {"s3:prefix": ["${aws:username}/*"]}}
    },
    {
      "Action": [
        "s3:GetObject",
        "s3:PutObject"
      ],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::users/${aws:username}/*"]
    }
  ]
}
```

#### Group
this will restrict a group to a folder called genericGroup, in users
when creating a new policy, we need to change the name genericGroup.


```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": ["s3:ListBucket"],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::users"],
      "Condition": {"StringLike": {"s3:prefix": ["genericGroup/*"]}}
    },
    {
      "Action": [
        "s3:GetObject",
        "s3:PutObject"
      ],
      "Effect": "Allow",
      "Resource": ["arn:aws:s3:::users/genericGroup/*"]
    }
  ]
}
```
