### ISSUE TITLE
Component: Load vocab from file

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/jsonld_forms#9]
Two needed.
* objects
* suggestions

**Comment by valentinedwv** [comment]
suggest list for first prototype For functions:
Aquisition... item
Aquisition... item2
Option... item
option... item

**Comment by smrgeoinfo** [comment]
The pick lists for ECRR controlled vocabularies are all SKOS files, ttl encoded, in the 
[EarthCube Resource Registry vocabularies organization](https://github.com/earthcubearchitecture-ecresourcereg).  I haven't migrated them to EarthCube organization. They are also all registered in the [ESIP Community Ontology Repository (COR)](http://cor.esipfed.org/ont#/), pick Ower = ~rduerr (upper left selection list)

**Comment by valentinedwv** [comment]
using the spreadsheet for now.[ ](https://docs.google.com/spreadsheets/d/1ykxgdeDjBzcTc1y64CuyaS2PhDuUtLuO5AFUehwhxDs/edit#gid=0)

**Comment by valentinedwv** [comment]
Loading from CSV files. multiple examples
